DROP PROCEDURE IF EXISTS BLOCK_ALTERNATE_ROWS;

DELIMITER $$

CREATE PROCEDURE BLOCK_ALTERNATE_ROWS ()
BEGIN
	UPDATE SEAT SET Is_Available = 0 WHERE ROW_No = 'B' OR ROW_No = 'D' OR ROW_No = 'F';
END $$

DELIMITER ;
