DROP PROCEDURE IF EXISTS THEATRE_REMOVAL;

DELIMITER $$

CREATE PROCEDURE THEATRE_REMOVAL (IN theatre_no INTEGER)

BEGIN
		UPDATE MOVIE_SHOW SET MOVIE_ID = NULL WHERE SCREEN_ID IN
			(SELECT SCREEN_ID FROM SCREEN WHERE THEATRE_ID=theatre_no);
            
		DELETE FROM SHOW_SEAT WHERE SHOW_ID IN 
			(SELECT SHOW_ID FROM MOVIE_SHOW WHERE SCREEN_ID IN
				(SELECT SCREEN_ID FROM SCREEN WHERE THEATRE_ID = theatre_no));
		
        DELETE FROM PAYMENT WHERE BOOKING_ID IN
			(SELECT BOOKING_ID FROM BOOKING WHERE SHOW_ID IN
				(SELECT SHOW_ID FROM MOVIE_SHOW WHERE SCREEN_ID IN
					(SELECT SCREEN_ID FROM SCREEN WHERE THEATRE_ID = theatre_no)));
                    
        DELETE FROM BOOKING WHERE SHOW_ID IN 
			(SELECT SHOW_ID FROM MOVIE_SHOW WHERE SCREEN_ID IN
				(SELECT SCREEN_ID FROM SCREEN WHERE THEATRE_ID = theatre_no));
                
        DELETE FROM MOVIE_SHOW WHERE SCREEN_ID IN
			(SELECT SCREEN_ID FROM SCREEN WHERE THEATRE_ID= theatre_no);
            
		DELETE FROM SEAT WHERE SCREEN_ID IN 
			(SELECT SCREEN_ID FROM SCREEN WHERE THEATRE_ID= theatre_no);
            
        DELETE FROM SCREEN WHERE THEATRE_ID= theatre_no;
        
        DELETE FROM EMPLOYEE WHERE THEATRE_ID= theatre_no;
        
        DELETE FROM THEATRE WHERE THEATRE_ID = theatre_no;
                
END$$

DELIMITER ;