DROP EVENT IF EXISTS SANITIZE_SHOW;

SET GLOBAL event_scheduler = ON;

CREATE EVENT SANITIZE_SHOW 
	ON SCHEDULE EVERY 1 MINUTE 
	STARTS CURRENT_TIMESTAMP + INTERVAL 1 MINUTE 
DO
		UPDATE MOVIE_SHOW SET Is_Sanitized =0 WHERE SHOW_Date = DATE_FORMAT(NOW(),'%Y-%m-%d')
        AND DATE_FORMAT(SHOW_Endtime, '%h:%i') = DATE_FORMAT(NOW(),'%h:%i');
	